---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: $APP_NAME
  namespace: $PROJECT_NAME
  labels:
    app: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME 
    spec:
      imagePullSecrets:
      - name: $SECRET_NAME 
      containers:
      - name: $APP_NAME 
        image: $IMAGE_NAME 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: $APP_PORT
          name: port1
          protocol: TCP
        volumeMounts:
          - name: applogs
            mountPath: $LOGPATH
        resources:
          requests:
            cpu: 0.25
            memory: 256Mi
          limits:
            cpu: 0.5
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: $HEALTHCHECK_PATH
            port: $APP_PORT
            scheme: HTTP
          initialDelaySeconds: 6
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: $HEALTHCHECK_PATH
            port: $APP_PORT
            scheme: HTTP
          initialDelaySeconds: 6
          timeoutSeconds: 5
          failureThreshold: 12
      volumes:
        - name: applogs
          hostPath:
            path: $LOGPATH


---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  namespace: $PROJECT_NAME
spec:
  type: ClusterIP
  selector:
    app: $APP_NAME 
  ports:
  - protocol: TCP
    port: $SVC_PORT
    targetPort: $APP_PORT

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $APP_NAME
  namespace: $PROJECT_NAME
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: $ING_HOST
    http:
      paths:
      - path: $ING_PATH
        backend:
          serviceName: $APP_NAME
          servicePort: $SVC_PORT
